# Generated by Django 5.1.3 on 2024-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='excerpt',
            field=models.CharField(max_length=500),
        ),
    ]
