# Generated by Django 5.1.3 on 2024-12-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_wish_item_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='AllOrder',
        ),
    ]
