# Generated by Django 5.1.3 on 2024-12-17 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_order_id_remove_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_address', models.CharField(max_length=500)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shipping_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('order_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.order_info'),
            preserve_default=False,
        ),
    ]
