# Generated by Django 5.1.3 on 2024-12-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_info_order_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
